### PR TITLE
android support

### PR DESCRIPTION
**Pull request by chirag04**

### CODE REVIEW

**Comment by chirag04** [comment]
@plrthink

**Comment by plrthink** [comment]
@chirag04  Sorry for the delay, it's awesome, I would check this as soon as possible.

**Comment by plrthink** [comment]
@chirag04 Code looks great, but can you please update the readme as well?

**Comment by chirag04** [comment]
@plrthink added readme instructions.

**Comment by plrthink** [comment]
@chirag04 Great

**Comment by chirag04** [comment]
@plrthink can you also bump the version on npm :+1:

**Comment by plrthink** [comment]
@chirag04 Sure~

**Comment by plrthink** [comment]
@chirag04 published. thx

**Pull request merged**
