### PR TITLE
Updated SSZipArchive 

### PR DESCRIPTION
**Pull request by itinance**
I came across that this library uses a very old version of SSZipArchive (from 2014). This PR will update SSZipArchive to the most recent version.

Make sure not to confuse with #17. Although the commit message includes the term "to fix linker issues", this does not belong to the newest issue #17, which seems to be cocoapods-related. 

I tested this PR with the conventional method (add files -> xcodeproj, add libz) and also with "react-native install", which is something like "npm install && rnpm link", while manually adding libz is still necessary because of still missing instructions. I will focus on this later on. I have not tested the installation with cocoapods. But the current pods-issues shouldn't be affected with this PR, wether less nor more, because it seems that there is another root cause for this.

### CODE REVIEW

**Comment by plrthink** [comment]
Cool!

The processing of installing this package is indeed sort of complicated since it needs users to manually add libz to the target. I think we could check how code-push handles this because they're also using ssziparchive.

Although this PR is great, I think we need to fix https://github.com/plrthink/react-native-zip-archive/issues/17 first since it is related to this one. So I may defer this one until we figure out how to handle ssziparchive.

**Comment by itinance** [comment]
Ok

**Comment by itinance** [comment]
I think there are two completely different things addressed here in the comments. One thing is #17 which has nothing to do with this PR, except that both occured at the nearly same time... and the other thing is that an really outdated version of SSZipArchive is used in current master. My PR moves forward the SSZipArchive-Version from 2014 to latest version. 
We should a) update SSZipArchive as soon as possible, which is solved with this PR, and b) look for a solution for #17 which you have already introduced (although it might not to be the final solution, if so)

**Comment by plrthink** [comment]
Ok, I would merge this PR. But it's relatively large so I need some time to test it. Hope merge it and release a new version before this weekend.

**Comment by itinance** [comment]
Yes, the people behind SSZipArchive refactored a lot in the last 2 years :) and they've added zip-password-support, which i plan to support also with this RN-library per pull request in a couple of weeks.

**Comment by plrthink** [comment]
@itinance sorry for my late response, will merge it now.

**Pull request merged**
