### PR TITLE
Unzip progress events

### PR DESCRIPTION
**Pull request by benvium**
Added ability for app to show progress of the unzip. Useful when unzipping larger files.

 Also took opportunity to improve the error messages sent from Native Android to JS.

### CODE REVIEW

**Comment by plrthink** [comment]
@benvium Cool.

Could you please rebase all this commits into a single one, I think that would be better.

**Comment by benvium** [comment]
@plrthink Yes, I'll do that. Thanks.

**Comment by plrthink** [comment]
@benvium I rebased that commits yesterday and also merged the pr. It's already in master branch. Sorry for not notifying you.

**Comment by benvium** [comment]
@plrthink Ah, great! thank you.

**Pull request closed without merging**
